### ISSUE TITLE
Add database backup

### ISSUE THREAD

**Issue by jirhiker** [NMWDI/WaterManagerDB#2]
add ability to backup database periodically. 

Also make entire database exportable as csv/excel files?

**Comment by chrisrycx** [comment]
We might want to consider using a cloud database service. This would deploy the database in the cloud with automatic back-ups. I haven't used Google Cloud, but it looks like this: https://cloud.google.com/sql would work.

**Comment by jirhiker** [comment]
That is how we have the st2 database setup.  I'm not necessarily opposed to that but the I was hoping to keep deployment of this app as containerized as possible. 

lets explore both options

**Comment by jirhiker** [comment]
There also is a strong desire from PVACD to have a local copy of their data. Obviously its a cloud world but if we could have a simple mechanism where csv files are automatically send to them or they can manually download them I think that will satisfy them.

**Comment by jirhiker** [comment]
added prodrigestivill/postgres-backup-local
