### ISSUE TITLE
Update meter related models to more closely match meter data

### ISSUE THREAD

**Issue by chrisrycx** [NMWDI/WaterManagerDB#26]
Changing columns in Meter table and adding table(s) for meter types

**Comment by chrisrycx** [comment]
@jirhiker What is "LU" seen in some tables: "MeterStatusLU"?

**Comment by chrisrycx** [comment]
PVACD has a "contact" field in their database Meter table... there is currently an Owners table. I think PVACD owns the vast majority of the meters, so a Contacts table might make more sense.

**Comment by jirhiker** [comment]
@chrisrycx LU = LookUp  as in Lookup table.  all the LU tables are essentially  `id,name,description`

**Comment by jirhiker** [comment]
I think I was using Owner to refer to the Owner of the well.  renaming to Contacts is probably better
