### ISSUE TITLE
Permissions problem on OSE endpoint

### ISSUE THREAD

**Issue by chrisrycx** [NMWDI/WaterManagerDB#44]
Both OSE user and Admin cannot access the ose endpoint. OSE user gives permissions issue and Admin user gives "unprocessible entry" error. Tested locally from /docs interface.

**Comment by chrisrycx** [comment]
If we could also remove "roles" from the /docs sign in that would be nice. I don't think they do anything at this point.

**Comment by zacharycarpenter** [comment]
I've added the OSE scope and given it to both the admin and OSE user. When testing in SwaggerUI I believe you need to use this format for datetimes '2020-09-15T15:53:00+05:00' and when testing with postman this format '2020-09-15T15%3A53%3A00%2B05%3A00'. I would think it should be working now.
